@echo off
setlocal

if "%DOG_REMOTE_SERVER_HOST%"=="" (
  echo Please set DOG_REMOTE_SERVER_HOST, DOG_REMOTE_SERVER_PORT, and DOG_REMOTE_SERVER_USER first.
  exit /b 1
)
if "%DOG_REMOTE_SERVER_PORT%"=="" set DOG_REMOTE_SERVER_PORT=22
if "%DOG_REMOTE_SERVER_USER%"=="" set DOG_REMOTE_SERVER_USER=mluser
if "%DOG_REMOTE_LOCAL_RK_PORT%"=="" set DOG_REMOTE_LOCAL_RK_PORT=2201
if "%DOG_REMOTE_LOCAL_ORIN_PORT%"=="" set DOG_REMOTE_LOCAL_ORIN_PORT=2202

start "dog-ssh-tunnel" cmd /k ssh -o ServerAliveInterval=30 -o ServerAliveCountMax=3 -p %DOG_REMOTE_SERVER_PORT% -L %DOG_REMOTE_LOCAL_RK_PORT%:127.0.0.1:60021 -L %DOG_REMOTE_LOCAL_ORIN_PORT%:127.0.0.1:60022 %DOG_REMOTE_SERVER_USER%@%DOG_REMOTE_SERVER_HOST%
timeout /t 2 >nul

set DOG_JUMP_HOST=127.0.0.1
set DOG_JUMP_PORT=%DOG_REMOTE_LOCAL_RK_PORT%
set DOG_ORIN_HOST=127.0.0.1
set DOG_ORIN_PORT=%DOG_REMOTE_LOCAL_ORIN_PORT%

cd /d "%~dp0dog_mvp_platform"
python server.py
