from django.urls import path

from .views import (
    AlertSkillBindingDetailView,
    AlertSkillBindingListView,
    AlertSkillPreviewView,
    CalendarDayDetailView,
    CalendarDayListCreateView,
    DashboardAnalyticsView,
    DashboardOverviewView,
    DeviceCommandPollView,
    DeviceCommandReportView,
    EventDetailView,
    EventHandleView,
    EventListView,
    LoginView,
    LogoutView,
    MediaUploadView,
    RobotAudioRecordingCommandView,
    RobotAudioCommandDetailView,
    RobotStreamAudioCommandView,
    RobotStreamAudioCommandDetailView,
    RobotRecordedAudioPlayView,
    RecordedAudioDetailView,
    RecordedAudioListView,
    RobotTTSCommandView,
    SpeechSynthesisView,
    SpeechCategoryDetailView,
    SpeechCategoryListCreateView,
    SpeechTemplateDetailView,
    SpeechTemplateListCreateView,
    ProfileView,
    RobotCommandView,
    RobotMcpTeleopView,
    RobotChargingDockView,
    RobotRemoteCommandDetailView,
    RobotDetailView,
    RobotListView,
    TaskListView,
    TelemetryIngestView,
    event_stream,
    health_check,
    MapDataListView,
    MapDataDetailView,
    MapDataDownloadView,
    MapDataSetActiveView,
    MapDataManualCleanView,
    MapDataLoopReviewView,
    MapDataLoopOptimizeView,
    MapDataMappingTraceView,
    MapDataSceneView,
    MapDataSceneSemanticsView,
    MapDataSceneSemanticsStatusView,
    MapDataSceneSemanticsReviewView,
    MapDataSceneCloudView,
    MapDataPreviewView,
    MapSetListView,
    DeviceMapUploadView,
    RobotMappingCancelView,
    RobotMappingBeginView,
    RobotMappingOriginCancelView,
    RobotMappingOriginExtractGlobalView,
    RobotMappingOriginStartView,
    RobotMappingOriginStatusView,
    RobotMappingSceneSemanticsView,
    RobotMappingSaveView,
    RobotMappingSlamStartView,
    RobotMappingStartView,
    RobotMappingSyncView,
    RobotMappingStatusView,
    RobotNavigationProbeView,
    RobotNavigationRecoverView,
    RobotNavigationRelocalizeView,
    RobotNavigationInitialPoseView,
    RobotNavigationSingleGoalView,
    RobotNavigationRestartView,
    RobotNavigationStartView,
    RobotNavigationStatusView,
    RobotNavigationStopView,
    RobotSystemLogListView,
    RobotSystemLogStreamView,
    RobotSystemLogDiagnosticEventView,
    RobotDebugLogSessionView,
    RobotDebugLogSessionDetailView,
    RobotSensorRestartView,
    PatrolRouteListView,
    PatrolRouteDetailView,
    PatrolRouteExecuteView,
    PatrolLoopSessionListCreateView,
    PatrolLoopSessionDetailView,
    PatrolLoopSessionPauseView,
    PatrolLoopSessionResumeView,
    PatrolLoopSessionContinueView,
    PatrolLoopSessionStopView,
    ZoneListView,
    ZoneDetailView,
    MapNavigationBoundaryView,
    MapNavigationBoundaryPublishView,
    TrackListView,
    TrackDetailView,
    RobotConnectionView,
    RobotMapDownloadView,
    AlertTimelineView,
    PatrolTaskDetailView,
    PatrolTaskExecuteView,
    PatrolTaskListCreateView,
    PatrolCalendarView,
    PatrolScheduleDetailView,
    PatrolScheduleDisableView,
    PatrolScheduleEnableView,
    PatrolScheduleListCreateView,
    PatrolScheduleRunNowView,
    RobotSessionListView,
    RobotStatusView,
    DevicePersonDetectionView,
    RobotPersonDetectionView,
    TaskExecutionCancelView,
    TaskExecutionForceExitView,
    TaskExecutionDetailView,
    TaskExecutionPauseView,
    TaskExecutionResumeView,
    TaskExecutionResumeForwardView,
    TaskExecutionTrajectoryView,
    ScheduleRunListView,
)
from .validation_views import (
    ValidationArtifactDownloadView,
    ValidationArtifactSignedDownloadView,
    ValidationJobApproveBaselineView,
    ValidationJobCancelView,
    ValidationJobDetailView,
    ValidationJobListCreateView,
    ValidationJobLiveTicketView,
    ValidationJobReportView,
    ValidationLiveTicketVerifyView,
    ValidationProfileListView,
    ValidationRecordingListCreateView,
    ValidationRecordingUploadCompleteView,
    ValidationRecordingUploadInitiateView,
    ValidationRecordingUploadPartsView,
    ValidationRunnerArtifactFinalizeView,
    ValidationRunnerArtifactPresignView,
    ValidationRunnerArtifactUploadView,
    ValidationRunnerClaimView,
    ValidationRunnerCompleteView,
    ValidationRunnerHeartbeatView,
    ValidationRunnerListView,
    ValidationRunnerSourceView,
)

urlpatterns = [
    path("health/", health_check),
    path("auth/login/", LoginView.as_view()),
    path("auth/logout/", LogoutView.as_view()),
    path("auth/profile/", ProfileView.as_view()),
    path("dashboard/overview/", DashboardOverviewView.as_view()),
    path("dashboard/analytics/", DashboardAnalyticsView.as_view()),
    path("robots/", RobotListView.as_view()),
    path("robots/<int:robot_id>/person-detections/", RobotPersonDetectionView.as_view()),
    path("robots/<int:robot_id>/", RobotDetailView.as_view()),
    path("robots/<int:robot_id>/commands/", RobotCommandView.as_view()),
    path("mcp/robots/<int:robot_id>/<str:category>/", RobotMcpTeleopView.as_view()),
    path("robots/<int:robot_id>/charging-dock/", RobotChargingDockView.as_view()),
    path("robots/<int:robot_id>/commands/<int:command_id>/", RobotAudioCommandDetailView.as_view()),
    path("robots/<int:robot_id>/commands/<uuid:command_id>/", RobotRemoteCommandDetailView.as_view()),
    path("robots/<int:robot_id>/commands/audio-recording/", RobotAudioRecordingCommandView.as_view()),
    path("robots/<int:robot_id>/commands/stream-audio/", RobotStreamAudioCommandView.as_view()),
    path("robots/<int:robot_id>/commands/stream-audio/<int:command_id>/", RobotStreamAudioCommandDetailView.as_view()),
    path("robots/<int:robot_id>/commands/recorded-audio/<int:recording_id>/", RobotRecordedAudioPlayView.as_view()),
    path("recorded-audio/", RecordedAudioListView.as_view()),
    path("recorded-audio/<int:pk>/", RecordedAudioDetailView.as_view()),
    path("robots/<int:robot_id>/commands/tts/", RobotTTSCommandView.as_view()),
    path("speech/synthesize/", SpeechSynthesisView.as_view()),
    path("speech-categories/", SpeechCategoryListCreateView.as_view()),
    path("speech-categories/<int:pk>/", SpeechCategoryDetailView.as_view()),
    path("speech-templates/", SpeechTemplateListCreateView.as_view()),
    path("speech-templates/<int:pk>/", SpeechTemplateDetailView.as_view()),
    path("alert-skills/", AlertSkillBindingListView.as_view()),
    path("alert-skills/<str:skill_key>/", AlertSkillBindingDetailView.as_view()),
    path("alert-skills/<str:skill_key>/preview/", AlertSkillPreviewView.as_view()),
    path("robots/<int:robot_id>/status/", RobotStatusView.as_view()),
    path("robots/<int:robot_id>/sessions/", RobotSessionListView.as_view()),
    path("robots/<int:robot_id>/mapping/status/", RobotMappingStatusView.as_view()),
    path("robots/<int:robot_id>/mapping/start/", RobotMappingStartView.as_view()),
    path("robots/<int:robot_id>/mapping/origin/status/", RobotMappingOriginStatusView.as_view()),
    path("robots/<int:robot_id>/mapping/origin/start/", RobotMappingOriginStartView.as_view()),
    path("robots/<int:robot_id>/mapping/origin/cancel/", RobotMappingOriginCancelView.as_view()),
    path("robots/<int:robot_id>/mapping/origin/extract-global/", RobotMappingOriginExtractGlobalView.as_view()),
    path("robots/<int:robot_id>/mapping/slam/start/", RobotMappingSlamStartView.as_view()),
    path("robots/<int:robot_id>/mapping/begin/", RobotMappingBeginView.as_view()),
    path("robots/<int:robot_id>/mapping/save/", RobotMappingSaveView.as_view()),
    path("robots/<int:robot_id>/mapping/cancel/", RobotMappingCancelView.as_view()),
    path("robots/<int:robot_id>/mapping/sync/", RobotMappingSyncView.as_view()),
    path("robots/<int:robot_id>/navigation/status/", RobotNavigationStatusView.as_view()),
    path("robots/<int:robot_id>/navigation/probe/", RobotNavigationProbeView.as_view()),
    path("robots/<int:robot_id>/navigation/start/", RobotNavigationStartView.as_view()),
    path("robots/<int:robot_id>/navigation/restart/", RobotNavigationRestartView.as_view()),
    path("robots/<int:robot_id>/navigation/recover/", RobotNavigationRecoverView.as_view()),
    path("robots/<int:robot_id>/navigation/relocalize/", RobotNavigationRelocalizeView.as_view()),
    path("robots/<int:robot_id>/navigation/initial-pose/", RobotNavigationInitialPoseView.as_view()),
    path("robots/<int:robot_id>/navigation/single-goal/", RobotNavigationSingleGoalView.as_view()),
    path("robots/<int:robot_id>/navigation/stop/", RobotNavigationStopView.as_view()),
    path("robots/<int:robot_id>/system-logs/", RobotSystemLogListView.as_view()),
    path("robots/<int:robot_id>/system-logs/stream/", RobotSystemLogStreamView.as_view()),
    path("robots/<int:robot_id>/system-logs/diagnostic-events/", RobotSystemLogDiagnosticEventView.as_view()),
    path("robots/<int:robot_id>/debug-log-sessions/", RobotDebugLogSessionView.as_view()),
    path("robots/<int:robot_id>/debug-log-sessions/<uuid:session_id>/", RobotDebugLogSessionDetailView.as_view()),
    path("robots/<int:robot_id>/sensors/restart/", RobotSensorRestartView.as_view()),
    path("events/", EventListView.as_view()),
    path("events/stream/", event_stream),
    path("events/<int:event_id>/", EventDetailView.as_view()),
    path("events/<int:event_id>/handle/", EventHandleView.as_view()),
    path("events/<uuid:event_id>/timeline/", AlertTimelineView.as_view()),
    path("tasks/", TaskListView.as_view()),
    path("patrol-tasks/", PatrolTaskListCreateView.as_view()),
    path("patrol-tasks/<int:task_id>/", PatrolTaskDetailView.as_view()),
    path("patrol-tasks/<int:task_id>/execute/", PatrolTaskExecuteView.as_view()),
    path("patrol-loop-sessions/", PatrolLoopSessionListCreateView.as_view()),
    path("patrol-loop-sessions/<uuid:session_id>/", PatrolLoopSessionDetailView.as_view()),
    path("patrol-loop-sessions/<uuid:session_id>/pause/", PatrolLoopSessionPauseView.as_view()),
    path("patrol-loop-sessions/<uuid:session_id>/resume/", PatrolLoopSessionResumeView.as_view()),
    path("patrol-loop-sessions/<uuid:session_id>/continue/", PatrolLoopSessionContinueView.as_view()),
    path("patrol-loop-sessions/<uuid:session_id>/stop/", PatrolLoopSessionStopView.as_view()),
    path("patrol-schedules/", PatrolScheduleListCreateView.as_view()),
    path("patrol-schedules/<int:pk>/", PatrolScheduleDetailView.as_view()),
    path("patrol-schedules/<int:pk>/enable/", PatrolScheduleEnableView.as_view()),
    path("patrol-schedules/<int:pk>/disable/", PatrolScheduleDisableView.as_view()),
    path("patrol-schedules/<int:pk>/run-now/", PatrolScheduleRunNowView.as_view()),
    path("calendar-days/", CalendarDayListCreateView.as_view()),
    path("calendar-days/<int:pk>/", CalendarDayDetailView.as_view()),
    path("patrol-calendar/", PatrolCalendarView.as_view()),
    path("schedule-runs/", ScheduleRunListView.as_view()),
    path("task-executions/<uuid:execution_id>/", TaskExecutionDetailView.as_view()),
    path("task-executions/<uuid:execution_id>/pause/", TaskExecutionPauseView.as_view()),
    path("task-executions/<uuid:execution_id>/resume/", TaskExecutionResumeView.as_view()),
    path("task-executions/<uuid:execution_id>/resume-forward/", TaskExecutionResumeForwardView.as_view()),
    path("task-executions/<uuid:execution_id>/cancel/", TaskExecutionCancelView.as_view()),
    path("task-executions/<uuid:execution_id>/force-exit/", TaskExecutionForceExitView.as_view()),
    path("task-executions/<uuid:execution_id>/trajectory/", TaskExecutionTrajectoryView.as_view()),
    path("telemetry/ingest/", TelemetryIngestView.as_view()),
    path("device/person-detections/", DevicePersonDetectionView.as_view()),
    path("device/media/upload/", MediaUploadView.as_view()),
    path("device/commands/poll/", DeviceCommandPollView.as_view()),
    path("device/commands/<int:command_id>/report/", DeviceCommandReportView.as_view()),
    path("device/maps/upload/", DeviceMapUploadView.as_view()),
    path("maps/", MapDataListView.as_view()),
    path("map-sets/", MapSetListView.as_view()),
    path("maps/<int:pk>/", MapDataDetailView.as_view()),
    path("maps/<int:pk>/download/", MapDataDownloadView.as_view()),
    path("maps/<int:pk>/set_active/", MapDataSetActiveView.as_view()),
    path("maps/<int:pk>/manual-clean/", MapDataManualCleanView.as_view()),
    path("maps/<int:pk>/loop-review/", MapDataLoopReviewView.as_view()),
    path("maps/<int:pk>/loop-optimize/", MapDataLoopOptimizeView.as_view()),
    path("maps/<int:pk>/preview/", MapDataPreviewView.as_view()),
    path("maps/<int:pk>/mapping-trace/", MapDataMappingTraceView.as_view()),
    path("maps/<int:pk>/scene/", MapDataSceneView.as_view()),
    path("maps/<int:pk>/scene-semantics/", MapDataSceneSemanticsView.as_view()),
    path("maps/<int:pk>/scene-semantics/status/", MapDataSceneSemanticsStatusView.as_view()),
    path("maps/<int:pk>/scene-semantics/review/", MapDataSceneSemanticsReviewView.as_view()),
    path("robots/<int:robot_id>/mapping/scene-semantics/", RobotMappingSceneSemanticsView.as_view()),
    path("maps/<int:pk>/scene-cloud/", MapDataSceneCloudView.as_view()),
    path("maps/robot/connect/", RobotConnectionView.as_view()),
    path("maps/robot/download/", RobotMapDownloadView.as_view()),
    path("routes/", PatrolRouteListView.as_view()),
    path("routes/<int:pk>/", PatrolRouteDetailView.as_view()),
    path("routes/<int:pk>/execute/", PatrolRouteExecuteView.as_view()),
    path("zones/", ZoneListView.as_view()),
    path("zones/<int:pk>/", ZoneDetailView.as_view()),
    path("maps/<int:map_id>/navigation-boundaries/", MapNavigationBoundaryView.as_view()),
    path("maps/<int:map_id>/navigation-boundaries/publish/", MapNavigationBoundaryPublishView.as_view()),
    path("tracks/", TrackListView.as_view()),
    path("tracks/<int:pk>/", TrackDetailView.as_view()),
    path("validation-recordings/", ValidationRecordingListCreateView.as_view()),
    path("validation-recordings/uploads/initiate/", ValidationRecordingUploadInitiateView.as_view()),
    path(
        "validation-recordings/<uuid:recording_id>/uploads/parts/",
        ValidationRecordingUploadPartsView.as_view(),
    ),
    path(
        "validation-recordings/<uuid:recording_id>/uploads/complete/",
        ValidationRecordingUploadCompleteView.as_view(),
    ),
    path("validation-profiles/", ValidationProfileListView.as_view()),
    path("validation-runners/", ValidationRunnerListView.as_view()),
    path("validation-jobs/", ValidationJobListCreateView.as_view()),
    path("validation-jobs/<uuid:job_id>/", ValidationJobDetailView.as_view()),
    path("validation-jobs/<uuid:job_id>/cancel/", ValidationJobCancelView.as_view()),
    path("validation-jobs/<uuid:job_id>/report/", ValidationJobReportView.as_view()),
    path("validation-jobs/<uuid:job_id>/live-ticket/", ValidationJobLiveTicketView.as_view()),
    path(
        "validation-jobs/<uuid:job_id>/approve-baseline/",
        ValidationJobApproveBaselineView.as_view(),
    ),
    path(
        "validation-jobs/<uuid:job_id>/artifacts/<uuid:artifact_id>/",
        ValidationArtifactDownloadView.as_view(),
    ),
    path(
        "validation-artifacts/<uuid:artifact_id>/signed/",
        ValidationArtifactSignedDownloadView.as_view(),
    ),
    path(
        "internal/validation-runners/<str:runner_id>/claim/",
        ValidationRunnerClaimView.as_view(),
    ),
    path("internal/validation-live-ticket/verify/", ValidationLiveTicketVerifyView.as_view()),
    path(
        "internal/validation-runners/<str:runner_id>/jobs/<uuid:job_id>/heartbeat/",
        ValidationRunnerHeartbeatView.as_view(),
    ),
    path(
        "internal/validation-runners/<str:runner_id>/jobs/<uuid:job_id>/complete/",
        ValidationRunnerCompleteView.as_view(),
    ),
    path("internal/validation-jobs/<uuid:job_id>/source/", ValidationRunnerSourceView.as_view()),
    path(
        "internal/validation-runners/<str:runner_id>/jobs/<uuid:job_id>/artifacts/",
        ValidationRunnerArtifactUploadView.as_view(),
    ),
    path(
        "internal/validation-runners/<str:runner_id>/jobs/<uuid:job_id>/artifacts/presign/",
        ValidationRunnerArtifactPresignView.as_view(),
    ),
    path(
        "internal/validation-runners/<str:runner_id>/jobs/<uuid:job_id>/artifacts/<uuid:artifact_id>/finalize/",
        ValidationRunnerArtifactFinalizeView.as_view(),
    ),
]
