# Generated by Django 6.0.4 on 2026-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("monitoring", "0026_mapdata_manual_cleanup")]

    operations = [
        migrations.AlterField(
            model_name="robotcommand",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "待发送"),
                    ("sent", "已发送"),
                    ("running", "执行中"),
                    ("finished", "已完成"),
                    ("failed", "发送失败"),
                    ("expired", "已过期"),
                    ("superseded", "已被新命令替换"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
    ]
