# Generated by Django 5.2.15 on 2026-08-14 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0043_alter_remotecommand_command_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='charging_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_robots', to='monitoring.mapdata'),
        ),
        migrations.AddField(
            model_name='robot',
            name='charging_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_robots', to='monitoring.patrolroute'),
        ),
    ]
