# Generated by Django 4.2 on 2026-08-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0057_mapdata_complete_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="mapdata",
            name="mapping_metrics",
            field=models.JSONField(blank=True, default=dict, verbose_name="建图指标"),
        ),
    ]
