# Generated by Django 5.2.17 on 2026-08-28 14:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_navigation_profile(apps, schema_editor):
    profile = apps.get_model('monitoring', 'ValidationProfile')
    profile.objects.get_or_create(
        name='navigation-localization',
        version=1,
        defaults={
            'mode': 'bag_replay',
            'enabled': True,
            'description': '导航定位 Bag 重算：输入完整性、TF、定位、路径和控制健康检查',
            'required_topics': [
                '/front_lidar', '/front_lidar/imu', '/tf', '/tf_static',
                '/odom/localization_odom', '/odom/nav2', '/cmd_vel', '/cmd_vel_raw',
            ],
            'replay_topics': [
                '/front_lidar', '/front_lidar/imu', '/fix', '/rtk_pvh',
                '/rtk/ntrip_status', '/tf_static', '/map', '/goal_pose',
            ],
            'output_topics': [
                '/tf', '/odom/localization_odom', '/odom/nav2', '/plan',
                '/transformed_global_plan', '/cmd_vel', '/cmd_vel_raw',
                '/status', '/localization/decision',
            ],
            'thresholds': {
                'topic_min_messages': 1,
                'max_timestamp_regressions': 0,
                'baseline_warn_ratio': 0.10,
                'baseline_fail_ratio': 0.20,
                'max_cmd_sign_flips_per_second': 2.0,
                'max_collision_intervention_ratio': 0.25,
            },
            'runner_config': {
                'replay_rate': 1.0,
                'clock_hz': 100,
                'timeout_multiplier': 3.0,
                'timeout_overhead_seconds': 600,
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0060_map_offline_optimize_command'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationRunner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('kind', models.CharField(choices=[('cpu', 'CPU Replay Runner'), ('matrix', 'MATRiX/UE GPU Runner')], default='cpu', max_length=16)),
                ('state', models.CharField(choices=[('offline', '离线'), ('idle', '空闲'), ('busy', '忙碌'), ('disabled', '停用')], default='offline', max_length=16)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('private_address', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ValidationProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('bag_replay', 'Bag 重算'), ('matrix_scenario', 'MATRiX/UE 场景仿真')], default='bag_replay', max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('required_topics', models.JSONField(blank=True, default=list)),
                ('replay_topics', models.JSONField(blank=True, default=list)),
                ('output_topics', models.JSONField(blank=True, default=list)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('runner_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name', '-version'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='uniq_validation_profile_ver')],
            },
        ),
        migrations.CreateModel(
            name='ValidationRecording',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=160)),
                ('storage_format', models.CharField(choices=[('mcap', 'MCAP'), ('sqlite3', 'rosbag2 SQLite3')], default='mcap', max_length=16)),
                ('state', models.CharField(choices=[('registered', '已登记'), ('uploading', '上传中'), ('ready', '可检查'), ('invalid', '无效')], default='registered', max_length=16)),
                ('object_key', models.CharField(blank=True, max_length=512)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('start_time_ns', models.BigIntegerField(default=0)),
                ('end_time_ns', models.BigIntegerField(default=0)),
                ('topic_manifest', models.JSONField(blank=True, default=list)),
                ('recording_manifest', models.JSONField(blank=True, default=dict)),
                ('source_path_hint', models.CharField(blank=True, max_length=512)),
                ('upload_id', models.CharField(blank=True, max_length=512)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('invalid_reason', models.TextField(blank=True)),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_recordings', to='monitoring.robot')),
                ('task_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_recordings', to='monitoring.taskexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('bag_replay', 'Bag 重算'), ('matrix_scenario', 'MATRiX/UE 场景仿真')], default='bag_replay', max_length=24)),
                ('state', models.CharField(choices=[('queued', '排队中'), ('staging', '准备中'), ('running', '运行中'), ('analyzing', '分析中'), ('uploading', '上传结果'), ('cancelling', '取消中'), ('completed', '已完成'), ('cancelled', '已取消'), ('infra_error', '基础设施失败')], default='queued', max_length=24)),
                ('verdict', models.CharField(choices=[('NOT_EVALUATED', '未判定'), ('PASS', '通过'), ('WARN', '告警'), ('FAIL', '失败')], default='NOT_EVALUATED', max_length=16)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_config', models.JSONField(blank=True, default=dict)),
                ('resolved_config', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('stack_git_sha', models.CharField(blank=True, max_length=64)),
                ('stack_image_digest', models.CharField(blank=True, max_length=160)),
                ('live_bridge_url', models.CharField(blank=True, max_length=512)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_jobs', to='monitoring.validationjob')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_jobs', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_jobs', to='monitoring.validationprofile')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_jobs', to='monitoring.validationrecording')),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_jobs', to='monitoring.validationrunner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(default='staging', max_length=24)),
                ('lease_token', models.UUIDField(default=uuid.uuid4)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('runtime_metrics', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='monitoring.validationjob')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='monitoring.validationrunner')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ValidationCheckResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PASS', '通过'), ('WARN', '告警'), ('FAIL', '失败'), ('NOT_EVALUATED', '未判定')], max_length=16)),
                ('severity', models.CharField(default='error', max_length=16)),
                ('hard_failure', models.BooleanField(default=False)),
                ('metric_name', models.CharField(blank=True, max_length=128)),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('start_time_ns', models.BigIntegerField(blank=True, null=True)),
                ('end_time_ns', models.BigIntegerField(blank=True, null=True)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='monitoring.validationjob')),
            ],
            options={
                'ordering': ['category', 'rule_id'],
                'constraints': [models.UniqueConstraint(fields=('job', 'rule_id'), name='uniq_validation_check')],
            },
        ),
        migrations.CreateModel(
            name='ValidationArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('source', '输入录制'), ('result_mcap', '结果 MCAP'), ('report', '检查报告'), ('log', '运行日志'), ('metrics', '指标'), ('evidence', '证据')], max_length=24)),
                ('name', models.CharField(max_length=256)),
                ('object_key', models.CharField(max_length=512)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='monitoring.validationjob')),
            ],
            options={
                'ordering': ['role', 'name'],
                'constraints': [models.UniqueConstraint(fields=('job', 'role', 'name'), name='uniq_validation_artifact')],
            },
        ),
        migrations.CreateModel(
            name='GoldenBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('map_hash', models.CharField(blank=True, max_length=64)),
                ('route_hash', models.CharField(blank=True, max_length=64)),
                ('stack_image_digest', models.CharField(max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_validation_baselines', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='golden_baseline', to='monitoring.validationjob')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='golden_baselines', to='monitoring.validationprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'active'], name='golden_profile_active_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='validationrecording',
            index=models.Index(fields=['state', '-created_at'], name='val_record_state_idx'),
        ),
        migrations.AddIndex(
            model_name='validationrecording',
            index=models.Index(fields=['robot', '-created_at'], name='val_record_robot_idx'),
        ),
        migrations.AddIndex(
            model_name='validationjob',
            index=models.Index(fields=['state', 'queued_at'], name='val_job_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='validationjob',
            index=models.Index(fields=['runner', 'state'], name='val_job_runner_idx'),
        ),
        migrations.AddConstraint(
            model_name='validationjob',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('requested_by', 'idempotency_key'), name='uniq_validation_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='validationjob',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), name='val_job_progress_range'),
        ),
        migrations.AddConstraint(
            model_name='validationattempt',
            constraint=models.UniqueConstraint(fields=('job', 'number'), name='uniq_validation_attempt'),
        ),
        migrations.RunPython(seed_navigation_profile, migrations.RunPython.noop),
    ]
