# Generated by Django 5.2.17 on 2026-08-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0067_taskexecution_loop_dispatch_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecommand',
            name='command_type',
            field=models.CharField(choices=[('task.start', '启动任务'), ('task.pause', '暂停任务'), ('task.resume', '继续任务'), ('task.resume_forward', '恢复前向'), ('task.cancel', '终止任务'), ('task.force_exit', '强制退出并清理任务'), ('mapping.start', '开始建图'), ('mapping.save', '停止并保存地图'), ('mapping.cancel', '取消建图'), ('mapping.status', '查询建图状态'), ('mapping.origin_start', '锁定 ENU 原点'), ('mapping.origin_cancel', '取消原点锁定'), ('mapping.origin_extract_global', '提取全局 ENU'), ('mapping.slam_start', '启动 SLAM 预热'), ('mapping.begin', '确认并开始正式建图'), ('nav.status', '查询导航状态'), ('nav.start', '启动导航栈'), ('nav.restart', '重启导航栈'), ('nav.recover', '恢复导航栈'), ('nav.stop', '停止导航栈'), ('nav.initial_pose', '设置初始定位'), ('nav.single_goal', '单点导航'), ('nav.relocalize', '主动重定位'), ('map.activate', '切换活动地图'), ('map.optimize', '离线回环优化'), ('sensor.restart', '重启传感器'), ('charge.start', '开始充电'), ('charge.stop', '断开充电'), ('motion.start', '启动运控'), ('motion.stop', '停止运控'), ('audio.volume', '调节扬声器音量'), ('teleop.takeover_enter', '进入远程接管'), ('teleop.takeover_exit', '退出远程接管'), ('teleop.stand_up', '站立'), ('teleop.lie_down', '趴下'), ('teleop.shake_hand', '打招呼'), ('teleop.two_leg_stand', '双腿站立'), ('teleop.crawl_forward', '匍匐前进'), ('teleop.speed_micro', '微速档'), ('teleop.speed_slow', '低速档'), ('teleop.speed_normal', '中速档'), ('teleop.speed_fast', '高速档'), ('teleop.move_forward', '前进'), ('teleop.move_backward', '后退'), ('teleop.move_left', '左移'), ('teleop.move_right', '右移'), ('teleop.turn_left', '左转'), ('teleop.turn_right', '右转'), ('teleop.move_velocity', '跟随速度'), ('teleop.move_stop', '停止移动'), ('teleop.passive', '软急停'), ('teleop.skill', '执行遥控技能'), ('teleop.skill_list', '列出遥控技能'), ('teleop.skill_status', '查询遥控技能'), ('teleop.skill_cancel', '取消遥控技能'), ('teleop.person_follow_start', '启动人员跟随'), ('teleop.person_follow_stop', '停止人员跟随'), ('teleop.person_follow_status', '查询人员跟随')], max_length=32),
        ),
    ]
