# Generated by Django 5.2.17 on 2026-09-11 04:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0074_unique_patrol_route_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolLoopSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_snapshot', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('starting', '准备启动'), ('running', '循环执行中'), ('resting', '轮间休息'), ('observing', '异常观察中'), ('recovering', '自愈中'), ('paused', '人工暂停'), ('stopping', '停止中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已停止'), ('low_battery_stopped', '低电量终止')], default='starting', max_length=32)),
                ('state_version', models.BigIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('rest_seconds', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('current_round', models.PositiveIntegerField(default=0)),
                ('next_action_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('observation_started_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_episode_id', models.UUIDField(blank=True, null=True)),
                ('recovery_reason_code', models.CharField(blank=True, max_length=64)),
                ('recovery_reason_message', models.TextField(blank=True)),
                ('recovery_attempt', models.PositiveSmallIntegerField(default=0)),
                ('recovery_max_attempts', models.PositiveSmallIntegerField(default=10)),
                ('manual_paused', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patrol_loop_sessions', to=settings.AUTH_USER_MODEL)),
                ('current_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owning_loop_sessions', to='monitoring.taskexecution')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patrol_loop_sessions', to='monitoring.robot')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loop_sessions', to='monitoring.patroltask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolLoopEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('starting', '准备启动'), ('running', '循环执行中'), ('resting', '轮间休息'), ('observing', '异常观察中'), ('recovering', '自愈中'), ('paused', '人工暂停'), ('stopping', '停止中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已停止'), ('low_battery_stopped', '低电量终止')], max_length=32)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('reason_message', models.TextField(blank=True)),
                ('recovery_attempt', models.PositiveSmallIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('task_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loop_events', to='monitoring.taskexecution')),
                ('loop_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitoring.patrolloopsession')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='patrolloopsession',
            index=models.Index(fields=['state', 'next_action_at'], name='loop_state_due_idx'),
        ),
        migrations.AddIndex(
            model_name='patrolloopsession',
            index=models.Index(fields=['robot', '-created_at'], name='loop_robot_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='patrolloopsession',
            constraint=models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0)), name='loop_duration_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='patrolloopsession',
            constraint=models.CheckConstraint(condition=models.Q(('recovery_attempt__lte', 10)), name='loop_recovery_attempt_lte_10'),
        ),
        migrations.AddConstraint(
            model_name='patrolloopsession',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['starting', 'running', 'resting', 'observing', 'recovering', 'paused', 'stopping'])), fields=('robot',), name='uniq_active_patrol_loop_per_robot'),
        ),
        migrations.AddIndex(
            model_name='patrolloopevent',
            index=models.Index(fields=['loop_session', '-occurred_at'], name='loop_event_recent_idx'),
        ),
    ]
