# Generated by Django 5.2.17 on 2026-09-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0076_low_battery_and_task_recovery"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="robottelemetry",
            index=models.Index(fields=["reported_at"], name="robottelemetry_reported_idx"),
        ),
        migrations.CreateModel(
            name="RobotTelemetryDailySummary",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField()),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("first_reported_at", models.DateTimeField()),
                ("last_reported_at", models.DateTimeField()),
                ("active_seconds", models.PositiveBigIntegerField(default=0)),
                ("distance_km", models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ("first_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("first_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("last_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ("last_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                (
                    "robot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_daily_summaries",
                        to="monitoring.robot",
                    ),
                ),
            ],
            options={
                "ordering": ["-day", "robot_id"],
                "indexes": [models.Index(fields=["day"], name="telemetry_summary_day_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("robot", "day"), name="uniq_robot_daily_telemetry")
                ],
            },
        ),
    ]
