# Generated by Django 4.2 on 2026-09-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0077_telemetry_daily_retention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="robot",
            name="control_mode",
            field=models.CharField(
                choices=[
                    ("unknown", "未知"),
                    ("autonomous", "自主"),
                    ("manual_assist", "人工辅助"),
                    ("manual_takeover", "人工接管"),
                    ("emergency_stop", "急停"),
                ],
                default="unknown",
                max_length=24,
            ),
        ),
    ]
