# Generated by Django 4.2 on 2026-09-12

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0080_scene_semantics_command"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapSceneInput",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("point_cloud", models.FileField(blank=True, null=True, upload_to="maps/scene-inputs/point-clouds/")),
                ("calibration", models.FileField(blank=True, null=True, upload_to="maps/scene-inputs/calibration/")),
                ("trajectory", models.FileField(blank=True, null=True, upload_to="maps/scene-inputs/trajectories/")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="map_scene_inputs", to=settings.AUTH_USER_MODEL)),
                ("map_data", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scene_inputs", to="monitoring.mapdata")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="MapSceneReference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(choices=[("image", "图片"), ("video", "视频"), ("recording", "RTAB/ROS录制")], max_length=16)),
                ("file", models.FileField(upload_to="maps/scene-inputs/references/")),
                ("original_name", models.CharField(max_length=256)),
                ("content_type", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("scene_input", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="references", to="monitoring.mapsceneinput")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="MapSceneBuild",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state", models.CharField(choices=[("queued", "等待执行"), ("running", "执行中"), ("review", "待审核"), ("ready", "已完成"), ("failed", "失败")], default="queued", max_length=16)),
                ("stage", models.CharField(default="queued", max_length=64)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("command_id", models.UUIDField(blank=True, null=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("anchors", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("artifact", models.FileField(blank=True, null=True, upload_to="maps/scene-builds/")),
                ("error_message", models.TextField(blank=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("map_data", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="scene_builds", to="monitoring.mapdata")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="map_scene_builds", to=settings.AUTH_USER_MODEL)),
                ("robot", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="scene_builds", to="monitoring.robot")),
                ("scene_input", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="builds", to="monitoring.mapsceneinput")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="mapscenebuild",
            index=models.Index(fields=["map_data", "-created_at"], name="scene_build_map_idx"),
        ),
    ]
