# Generated by Django 5.2.17 on 2026-09-14 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0083_server_scene_build_worker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleDetectionTestRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', '待执行'), ('running', '执行中'), ('finished', '已完成'), ('failed', '失败'), ('expired', '已过期')], default='queued', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bicycle_detection_test_runs', to=settings.AUTH_USER_MODEL)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bicycle_detection_test_runs', to='monitoring.robot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BicycleDetectionTestImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='bicycle-detection-tests/%Y/%m/%d/input/')),
                ('annotated_file', models.FileField(blank=True, upload_to='bicycle-detection-tests/%Y/%m/%d/output/')),
                ('status', models.CharField(choices=[('queued', '待执行'), ('running', '执行中'), ('finished', '已完成'), ('failed', '失败'), ('expired', '已过期')], default='queued', max_length=16)),
                ('result_code', models.CharField(blank=True, max_length=32)),
                ('detected_class', models.CharField(blank=True, max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('bbox', models.JSONField(blank=True, default=dict)),
                ('bbox_area', models.PositiveIntegerField(blank=True, null=True)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='monitoring.bicycledetectiontestrun')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='bicycledetectiontestrun',
            index=models.Index(fields=['robot', 'status', 'expires_at'], name='monitoring__robot_i_cc7c53_idx'),
        ),
        migrations.AddConstraint(
            model_name='bicycledetectiontestimage',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_bicycle_test_run_sequence'),
        ),
    ]
