#!/usr/bin/env bash
set -euo pipefail

export BAG_ROOT="${BAG_ROOT:-/home/dogrobot/runtime/nx-edge/data/rosbags/navigation}"
export STATE_DIR="${STATE_DIR:-/tmp/roamerx_navigation_rosbag}"
# Navigation diagnostics are incident data, not a long-term archive. Keep the
# latest task by default, cap both the retained root and an individual task at
# 10 GiB, and collect task-scoped system/process metrics alongside the MCAP.
export BAG_KEEP_RECENT="${BAG_KEEP_RECENT:-1}"
export BAG_MAX_AGE_DAYS="${BAG_MAX_AGE_DAYS:-0}"
export BAG_MAX_TOTAL_GIB="${BAG_MAX_TOTAL_GIB:-10}"
export MAX_SESSION_GIB="${MAX_SESSION_GIB:-10}"
export PRUNE_AFTER_STOP="${PRUNE_AFTER_STOP:-1}"
export RESOURCE_METRICS_ENABLED="${RESOURCE_METRICS_ENABLED:-1}"
# /odom/nav2 is not a relay of /odom/localization_odom: tf_publisher flattens
# roll/pitch (yawOnly) before republishing, and navigo_params.yaml points both
# planner_server and controller_server at it. It is the pose Nav2 actually
# consumed, so a replay that only has /odom/localization_odom cannot explain
# Nav2 behaviour.
# /plan is the global path from planner_server; /transformed_global_plan is the
# pruned segment MPPI was tracking (see navigo_mppi_controller/controller.cpp).
# /cmd_vel_raw -> /cmd_vel spans collision_monitor, so its interventions show up
# as the difference between the two.
# /status carries the scan-match quality flags but only a frame-to-frame delta
# pose, so /localization/scan_match_pose carries the absolute NDT/VGICP result.
export ROSBAG_EXTRA_TOPICS="${ROSBAG_EXTRA_TOPICS:-/localization_info /localization/decision /localization/policy /status /localization/scan_match_pose /laser_scan /odom/nav2 /plan /transformed_global_plan /cmd_vel_nav /local_costmap/costmap_raw /polygon_stop /polygon_slowdown /sensor_health /mppi/performance /trajectories}"

BASE_RECORDER="$(dirname "$0")/mapping_rosbag.sh"
AVOIDANCE_SUMMARY_TOOL="${AVOIDANCE_SUMMARY_TOOL:-$(dirname "$0")/summarize_avoidance_bag.py}"

if [ "${1:-status}" != "stop" ]; then
  exec "${BASE_RECORDER}" "$@"
fi

# Keep mapping_rosbag.sh's final JSON line intact for Edge Agent callers while
# enriching the closed task directory with deterministic avoidance metrics.
output="$("${BASE_RECORDER}" "$@")"
if [ -f "${STATE_DIR}/session.env" ]; then
  # Generated by mapping_rosbag.sh with shell-escaped local paths.
  source "${STATE_DIR}/session.env"
  if [ "${AVOIDANCE_SUMMARY_ENABLED:-1}" = "1" ] &&
     [ -n "${BAG_DIR:-}" ] && [ -f "${BAG_DIR}/metadata.yaml" ] &&
     [ -f "${AVOIDANCE_SUMMARY_TOOL}" ]; then
    if [ "${AVOIDANCE_SUMMARY_SYNC:-0}" = "1" ]; then
      if ! python3 "${AVOIDANCE_SUMMARY_TOOL}" "${BAG_DIR}" \
        --output "${BAG_DIR}/avoidance_summary.json" >/dev/null; then
        echo "WARNING: failed to summarize avoidance diagnostics for ${BAG_DIR}" >&2
      fi
    else
      # A task bag may be many GiB. Keep task cancellation/terminal reporting
      # bounded by summarizing after the recorder has returned its final JSON.
      setsid nice -n 10 python3 "${AVOIDANCE_SUMMARY_TOOL}" "${BAG_DIR}" \
        --output "${BAG_DIR}/avoidance_summary.json" \
        >"${BAG_DIR}/avoidance_summary.log" 2>&1 < /dev/null &
      printf '%s\n' "$!" >"${BAG_DIR}/avoidance_summary.pid"
    fi
  fi
fi
printf '%s\n' "${output}"
