from django.urls import path

from .views import (
    CalendarDayDetailView,
    CalendarDayListCreateView,
    DashboardAnalyticsView,
    DashboardOverviewView,
    EventDetailView,
    EventHandleView,
    EventListView,
    LoginView,
    LogoutView,
    MediaUploadView,
    ProfileView,
    RobotCommandView,
    RobotDetailView,
    RobotListView,
    TaskListView,
    TelemetryIngestView,
    event_stream,
    health_check,
    MapDataListView,
    MapDataDetailView,
    MapDataDownloadView,
    MapDataSetActiveView,
    MapDataPreviewView,
    DeviceMapUploadView,
    RobotMappingCancelView,
    RobotMappingSaveView,
    RobotMappingStartView,
    RobotMappingSyncView,
    RobotMappingStatusView,
    RobotNavigationProbeView,
    RobotNavigationRecoverView,
    RobotNavigationInitialPoseView,
    RobotNavigationRestartView,
    RobotNavigationStartView,
    RobotNavigationStatusView,
    RobotNavigationStopView,
    PatrolRouteListView,
    PatrolRouteDetailView,
    PatrolRouteExecuteView,
    ZoneListView,
    ZoneDetailView,
    TrackListView,
    TrackDetailView,
    RobotConnectionView,
    RobotMapDownloadView,
    AlertTimelineView,
    PatrolTaskDetailView,
    PatrolTaskExecuteView,
    PatrolTaskListCreateView,
    PatrolCalendarView,
    PatrolScheduleDetailView,
    PatrolScheduleDisableView,
    PatrolScheduleEnableView,
    PatrolScheduleListCreateView,
    PatrolScheduleRunNowView,
    RobotSessionListView,
    RobotStatusView,
    TaskExecutionCancelView,
    TaskExecutionDetailView,
    TaskExecutionPauseView,
    TaskExecutionResumeView,
    TaskExecutionTrajectoryView,
    ScheduleRunListView,
)

urlpatterns = [
    path("health/", health_check),
    path("auth/login/", LoginView.as_view()),
    path("auth/logout/", LogoutView.as_view()),
    path("auth/profile/", ProfileView.as_view()),
    path("dashboard/overview/", DashboardOverviewView.as_view()),
    path("dashboard/analytics/", DashboardAnalyticsView.as_view()),
    path("robots/", RobotListView.as_view()),
    path("robots/<int:robot_id>/", RobotDetailView.as_view()),
    path("robots/<int:robot_id>/commands/", RobotCommandView.as_view()),
    path("robots/<int:robot_id>/status/", RobotStatusView.as_view()),
    path("robots/<int:robot_id>/sessions/", RobotSessionListView.as_view()),
    path("robots/<int:robot_id>/mapping/status/", RobotMappingStatusView.as_view()),
    path("robots/<int:robot_id>/mapping/start/", RobotMappingStartView.as_view()),
    path("robots/<int:robot_id>/mapping/save/", RobotMappingSaveView.as_view()),
    path("robots/<int:robot_id>/mapping/cancel/", RobotMappingCancelView.as_view()),
    path("robots/<int:robot_id>/mapping/sync/", RobotMappingSyncView.as_view()),
    path("robots/<int:robot_id>/navigation/status/", RobotNavigationStatusView.as_view()),
    path("robots/<int:robot_id>/navigation/probe/", RobotNavigationProbeView.as_view()),
    path("robots/<int:robot_id>/navigation/start/", RobotNavigationStartView.as_view()),
    path("robots/<int:robot_id>/navigation/restart/", RobotNavigationRestartView.as_view()),
    path("robots/<int:robot_id>/navigation/recover/", RobotNavigationRecoverView.as_view()),
    path("robots/<int:robot_id>/navigation/initial-pose/", RobotNavigationInitialPoseView.as_view()),
    path("robots/<int:robot_id>/navigation/stop/", RobotNavigationStopView.as_view()),
    path("events/", EventListView.as_view()),
    path("events/stream/", event_stream),
    path("events/<int:event_id>/", EventDetailView.as_view()),
    path("events/<int:event_id>/handle/", EventHandleView.as_view()),
    path("events/<uuid:event_id>/timeline/", AlertTimelineView.as_view()),
    path("tasks/", TaskListView.as_view()),
    path("patrol-tasks/", PatrolTaskListCreateView.as_view()),
    path("patrol-tasks/<int:task_id>/", PatrolTaskDetailView.as_view()),
    path("patrol-tasks/<int:task_id>/execute/", PatrolTaskExecuteView.as_view()),
    path("patrol-schedules/", PatrolScheduleListCreateView.as_view()),
    path("patrol-schedules/<int:pk>/", PatrolScheduleDetailView.as_view()),
    path("patrol-schedules/<int:pk>/enable/", PatrolScheduleEnableView.as_view()),
    path("patrol-schedules/<int:pk>/disable/", PatrolScheduleDisableView.as_view()),
    path("patrol-schedules/<int:pk>/run-now/", PatrolScheduleRunNowView.as_view()),
    path("calendar-days/", CalendarDayListCreateView.as_view()),
    path("calendar-days/<int:pk>/", CalendarDayDetailView.as_view()),
    path("patrol-calendar/", PatrolCalendarView.as_view()),
    path("schedule-runs/", ScheduleRunListView.as_view()),
    path("task-executions/<uuid:execution_id>/", TaskExecutionDetailView.as_view()),
    path("task-executions/<uuid:execution_id>/pause/", TaskExecutionPauseView.as_view()),
    path("task-executions/<uuid:execution_id>/resume/", TaskExecutionResumeView.as_view()),
    path("task-executions/<uuid:execution_id>/cancel/", TaskExecutionCancelView.as_view()),
    path("task-executions/<uuid:execution_id>/trajectory/", TaskExecutionTrajectoryView.as_view()),
    path("telemetry/ingest/", TelemetryIngestView.as_view()),
    path("device/media/upload/", MediaUploadView.as_view()),
    path("device/maps/upload/", DeviceMapUploadView.as_view()),
    path("maps/", MapDataListView.as_view()),
    path("maps/<int:pk>/", MapDataDetailView.as_view()),
    path("maps/<int:pk>/download/", MapDataDownloadView.as_view()),
    path("maps/<int:pk>/set_active/", MapDataSetActiveView.as_view()),
    path("maps/<int:pk>/preview/", MapDataPreviewView.as_view()),
    path("maps/robot/connect/", RobotConnectionView.as_view()),
    path("maps/robot/download/", RobotMapDownloadView.as_view()),
    path("routes/", PatrolRouteListView.as_view()),
    path("routes/<int:pk>/", PatrolRouteDetailView.as_view()),
    path("routes/<int:pk>/execute/", PatrolRouteExecuteView.as_view()),
    path("zones/", ZoneListView.as_view()),
    path("zones/<int:pk>/", ZoneDetailView.as_view()),
    path("tracks/", TrackListView.as_view()),
    path("tracks/<int:pk>/", TrackDetailView.as_view()),
]
