from django.urls import path

from .views import (
    DashboardAnalyticsView,
    DashboardOverviewView,
    DeviceCommandPollView,
    DeviceCommandReportView,
    EventDetailView,
    EventHandleView,
    EventListView,
    LoginView,
    LogoutView,
    MediaUploadView,
    RobotAudioRecordingCommandView,
    ProfileView,
    RobotCommandView,
    RobotDetailView,
    RobotListView,
    TaskListView,
    TelemetryIngestView,
    event_stream,
    health_check,
    MapDataListView,
    MapDataDetailView,
    MapDataDownloadView,
    MapDataSetActiveView,
    MapDataPreviewView,
    PatrolRouteListView,
    PatrolRouteDetailView,
    ZoneListView,
    ZoneDetailView,
    TrackListView,
    TrackDetailView,
    RobotConnectionView,
    RobotMapDownloadView,
)

urlpatterns = [
    path("health/", health_check),
    path("auth/login/", LoginView.as_view()),
    path("auth/logout/", LogoutView.as_view()),
    path("auth/profile/", ProfileView.as_view()),
    path("dashboard/overview/", DashboardOverviewView.as_view()),
    path("dashboard/analytics/", DashboardAnalyticsView.as_view()),
    path("robots/", RobotListView.as_view()),
    path("robots/<int:robot_id>/", RobotDetailView.as_view()),
    path("robots/<int:robot_id>/commands/", RobotCommandView.as_view()),
    path("robots/<int:robot_id>/commands/audio-recording/", RobotAudioRecordingCommandView.as_view()),
    path("events/", EventListView.as_view()),
    path("events/stream/", event_stream),
    path("events/<int:event_id>/", EventDetailView.as_view()),
    path("events/<int:event_id>/handle/", EventHandleView.as_view()),
    path("tasks/", TaskListView.as_view()),
    path("telemetry/ingest/", TelemetryIngestView.as_view()),
    path("device/media/upload/", MediaUploadView.as_view()),
    path("device/commands/poll/", DeviceCommandPollView.as_view()),
    path("device/commands/<int:command_id>/report/", DeviceCommandReportView.as_view()),
    path("maps/", MapDataListView.as_view()),
    path("maps/<int:pk>/", MapDataDetailView.as_view()),
    path("maps/<int:pk>/download/", MapDataDownloadView.as_view()),
    path("maps/<int:pk>/set_active/", MapDataSetActiveView.as_view()),
    path("maps/<int:pk>/preview/", MapDataPreviewView.as_view()),
    path("maps/robot/connect/", RobotConnectionView.as_view()),
    path("maps/robot/download/", RobotMapDownloadView.as_view()),
    path("routes/", PatrolRouteListView.as_view()),
    path("routes/<int:pk>/", PatrolRouteDetailView.as_view()),
    path("zones/", ZoneListView.as_view()),
    path("zones/<int:pk>/", ZoneDetailView.as_view()),
    path("tracks/", TrackListView.as_view()),
    path("tracks/<int:pk>/", TrackDetailView.as_view()),
]
