# Generated by Django 6.0.4 on 2026-05-15 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionevent',
            name='bbox_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='bbox_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='bbox_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='bbox_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='camera_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='frame_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='frame_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='object_class',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='raw_detection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='stream_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='inspectionevent',
            name='track_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='robot',
            name='camera_id',
            field=models.CharField(default='front', max_length=32),
        ),
        migrations.AddField(
            model_name='robot',
            name='play_urls',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='robot',
            name='stream_id',
            field=models.CharField(blank=True, max_length=96),
        ),
        migrations.AddField(
            model_name='robottelemetry',
            name='video',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='robottelemetry',
            name='sequence_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('snapshot', '抓拍图'), ('clip', '视频片段')], max_length=16)),
                ('camera_id', models.CharField(blank=True, max_length=32)),
                ('sequence_id', models.CharField(blank=True, max_length=64)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='device-media/%Y/%m/%d/')),
                ('url', models.URLField(blank=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='monitoring.robot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
