# Generated by Django 6.0.6 on 2026-06-18 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_add_takeover_command_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='地图名称')),
                ('pgm_file', models.FileField(blank=True, null=True, upload_to='maps/', verbose_name='PGM地图文件')),
                ('yaml_file', models.FileField(blank=True, null=True, upload_to='maps/', verbose_name='YAML配置文件')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='maps/thumbnails/', verbose_name='缩略图')),
                ('resolution', models.FloatField(default=0.05, verbose_name='分辨率(m/像素)')),
                ('width', models.IntegerField(default=0, verbose_name='宽度(像素)')),
                ('height', models.IntegerField(default=0, verbose_name='高度(像素)')),
                ('origin', models.JSONField(default=list, verbose_name='原点坐标 [x, y, theta]')),
                ('active', models.BooleanField(default=False, verbose_name='是否为活动地图')),
                ('description', models.TextField(blank=True, verbose_name='地图描述')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maps', to='monitoring.robot', verbose_name='关联机器人')),
            ],
            options={
                'verbose_name': '地图数据',
                'verbose_name_plural': '地图数据',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='路线名称')),
                ('waypoints', models.JSONField(default=list, verbose_name='途经点坐标数组')),
                ('waypoint_names', models.JSONField(default=list, verbose_name='途经点名称数组')),
                ('description', models.TextField(blank=True, verbose_name='路线描述')),
                ('map_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='monitoring.mapdata', verbose_name='关联地图')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='monitoring.robot', verbose_name='关联机器人')),
            ],
            options={
                'verbose_name': '巡逻路线',
                'verbose_name_plural': '巡逻路线',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.JSONField(default=list, verbose_name='轨迹路径 [[x1,y1,timestamp1],[x2,y2,timestamp2],...]')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('distance', models.FloatField(default=0, verbose_name='行驶距离(米)')),
                ('duration', models.IntegerField(default=0, verbose_name='持续时间(秒)')),
                ('description', models.TextField(blank=True, verbose_name='轨迹描述')),
                ('map_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='monitoring.mapdata', verbose_name='关联地图')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='monitoring.robot', verbose_name='关联机器人')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='monitoring.patrolroute', verbose_name='关联路线')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='monitoring.patroltask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '轨迹记录',
                'verbose_name_plural': '轨迹记录',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, verbose_name='禁区名称')),
                ('zone_type', models.CharField(choices=[('forbidden', '禁入区'), ('warning', '警告区'), ('restricted', '限行区')], default='forbidden', max_length=16, verbose_name='禁区类型')),
                ('polygon', models.JSONField(default=list, verbose_name='多边形坐标点 [[x1,y1],[x2,y2],...]')),
                ('description', models.TextField(blank=True, verbose_name='禁区描述')),
                ('active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('map_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='monitoring.mapdata', verbose_name='关联地图')),
            ],
            options={
                'verbose_name': '禁区',
                'verbose_name_plural': '禁区',
                'ordering': ['-created_at'],
            },
        ),
    ]
