# Generated by Django 5.2.15 on 2026-07-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_play_audio_command'),
        ('monitoring', '0021_add_teleop_remote_commands'),
    ]

    operations = [
    ]
